"""
!!! DO NOT EDIT THIS FILE !!!
"""
import unittest
import aufgabe_1, aufgabe_2


class AufgabenPruefen_Aufgabe_1(unittest.TestCase):
    def test_add_numbers(self):
        self.assertEqual(aufgabe_1.add_numbers(1, 2), 3)
        self.assertEqual(aufgabe_1.add_numbers(1075.046, 3.1415), 1078.1875)
    def test_rectangle_calculate_area(self):
        self.assertEqual(aufgabe_1.rectangle_calculate_area(3, 4), 12)
        self.assertEqual(aufgabe_1.rectangle_calculate_area(10.764, 7.432), 79.998048)

class AufgabenPruefen_Aufgabe_2(unittest.TestCase):
    def test_get_primenumbers(self):
        self.assertEqual(aufgabe_2.get_primenumbers(7), [2, 3, 5, 7])
        self.assertEqual(aufgabe_2.get_primenumbers(19), [2, 3, 5, 7, 11, 13, 17, 19])
        self.assertEqual(aufgabe_2.get_primenumbers(1), [])
        self.assertEqual(aufgabe_2.get_primenumbers(2), [2])
        self.assertEqual(aufgabe_2.get_primenumbers(30), [2, 3, 5, 7, 11, 13, 17, 19, 23, 29])


if __name__ == "__main__":
    unittest.main(verbosity=2)
